import { Order } from "@/types/orders/orderType";
import { ReplacementRequest } from "@/types/orders/requestType";

export const orders: Order | any[] = [
  {
    orderId: 45678920,
    orderDateTime: "2025-07-01T08:15:00Z",
    orderProgress: "Completed",
    orderStatus: "Pending",
    deliveryType: "delivery",
    deliveryDate: "2025-07-03",
    deliveryId: 50001,
    deliveryCost: 5.0,
    GST: 500.0,
    paymentHistory: {
      total: 550.0,
      date: "2025-07-01T08:17:00Z",
      transactionId: "pi_1ABC234DEF567",
      via: "PayPal",
    },
    driverInfo: {
      name: "Alice Martin",
      mobile: "+61400111222",
    },
    jobRefrence: {
      code: "JR001",
      projectName: "City Mall Fitout",
    },
    address: {
      addressId: "addr001",
      title: "Site Office",
      streetAddress: "45 King St",
      suburb: "Sydney",
      state: "NSW",
      postcode: "2000",
    },
    recipientInfo: {
      recipientName: "Bob Lee",
      recipientMobile: "+61400999888",
    },
    flashings: [
      {
        flashingId: "hw2k",
        material: "Copper",
        color: "Black Matte",
        thickness: 1.2,
        totalGirth: 600,
        code: "FL-A1",
        position: "A1",
        crushfold: false,
        tapered: false,
        sepcifications: [
          {
            pieceId: "hw2kl0o8",
            quantity: 2,
            length: 2000,
            cost: 1200.0,
          },
          {
            pieceId: "hw2k123s",
            quantity: 4,
            length: 1250,
            cost: 1200.0,
          },
        ],
      },
      {
        flashingId: "a5s6d",
        material: "Stainless Steel",
        color: "Steel",
        thickness: 1.5,
        totalGirth: 700,
        code: "FL-A1",
        position: "A1",
        crushfold: false,
        tapered: false,
        sepcifications: [
          {
            pieceId: "a5s6d12sa",
            quantity: 2,
            length: 2000,
            cost: 1200.0,
          },
          {
            pieceId: "a5s6dghu7",
            quantity: 4,
            length: 300,
            cost: 1200.0,
          },
        ],
      },
    ],
  },
  // 1. Pending Delivery, Order Received
  {
    orderId: 100001,
    orderDateTime: "2025-07-01T08:15:00Z",
    orderProgress: "Completed",
    orderStatus: "Completed",
    deliveryType: "delivery",
    deliveryDate: "2025-07-03",
    deliveryId: 50001,
    deliveryCost: 5.0,
    GST: 500.0,
    paymentHistory: {
      total: 550.0,
      date: "2025-07-01T08:17:00Z",
      transactionId: "pi_1ABC234DEF567",
      via: "PayPal",
    },
    driverInfo: {
      name: "Alice Martin",
      mobile: "+61400111222",
    },
    jobRefrence: {
      code: "JR001",
      projectName: "City Mall Fitout",
    },
    address: {
      addressId: "addr001",
      title: "Site Office",
      streetAddress: "45 King St",
      suburb: "Sydney",
      state: "NSW",
      postcode: "2000",
    },
    recipientInfo: {
      recipientName: "Bob Lee",
      recipientMobile: "+61400999888",
    },
    flashings: [
      {
        flashingId: "fl001",
        code: "FL-A1",
        position: "A1",
        material: "Aluminum",
        color: "Silver",
        thickness: 1.2,
        crushfold: false,
        tapered: false,
        totalGirth: 600,
        sepcifications: [
          {
            pieceId: "p001",
            quantity: 10,
            length: 150,
            cost: 300.0,
          },
        ],
      },
    ],
  },
  // 2. In Production Delivery, In Production
  {
    orderId: 100002,
    orderDateTime: "2025-07-02T12:00:00Z",
    orderProgress: "In Production",
    orderStatus: "In Production",
    deliveryType: "delivery",
    deliveryDate: "2025-07-05",
    deliveryId: 50002,
    deliveryCost: 8.5,
    GST: 850.0,
    paymentHistory: {
      total: 935.0,
      date: "2025-07-02T12:05:00Z",
      transactionId: "pi_2GHI789JKL012",
      via: "Card",
    },
    driverInfo: {
      name: "Carlos Ruiz",
      mobile: "+61400777666",
    },
    jobRefrence: {
      code: "JR002",
      projectName: "Harbour Bridge Maintenance",
    },
    address: {
      addressId: "addr002",
      title: "Maintenance Yard",
      streetAddress: "1 Bridge Rd",
      suburb: "Sydney",
      state: "NSW",
      postcode: "2009",
    },
    recipientInfo: {
      recipientName: "Dana Scott",
      recipientMobile: "+61400666555",
    },
    flashings: [
      {
        flashingId: "fl002",
        code: "FL-B2",
        position: "B2",
        material: "Copper",
        color: "Copper Red",
        thickness: 1.8,
        crushfold: true,
        tapered: true,
        totalGirth: 750,
        sepcifications: [
          { pieceId: "p002", quantity: 5, length: 400, cost: 450.0 },
          { pieceId: "p003", quantity: 3, length: 800, cost: 540.0 },
        ],
      },
    ],
  },
  // 3. Ready Pickup, Ready for pickup
  {
    orderId: 100003,
    orderDateTime: "2025-07-03T09:30:00Z",
    orderProgress: "Ready",
    orderStatus: "Ready for pickup",
    deliveryType: "pickup",
    deliveryDate: "2025-07-04",
    deliveryId: 50003,
    deliveryCost: 0.0,
    GST: 0.0,
    paymentHistory: {
      total: 250.0,
      date: "2025-07-03T09:35:00Z",
      transactionId: "pi_3MNO345PQR678",
      via: "Bank Transfer",
    },
    driverInfo: { name: "Elaine Wong", mobile: "+61400555444" },
    jobRefrence: { code: "JR003", projectName: "Warehouse Setup" },
    pickupInfo: {
      addressId: "pu001",
      title: "Main Depot",
      streetAddress: "200 Industrial Ave",
      suburb: "Melbourne",
      state: "VIC",
      postcode: "3000",
      description: "Open: 8am - 6pm",
    },
    recipientInfo: {
      recipientName: "Frank Lee",
      recipientMobile: "+61312345678",
    },
    flashings: [
      {
        flashingId: "fl003",
        code: "FL-C3",
        position: "C3",
        material: "Steel",
        color: "Black",
        thickness: 2.0,
        crushfold: false,
        tapered: false,
        totalGirth: 900,
        sepcifications: [
          { pieceId: "p004", quantity: 8, length: 500, cost: 800.0 },
        ],
      },
    ],
  },
  // 4. On the way Delivery, On the way
  {
    orderId: 100004,
    orderDateTime: "2025-07-04T07:45:00Z",
    orderProgress: "Ready",
    orderStatus: "On the way",
    deliveryType: "delivery",
    deliveryDate: "2025-07-06",
    deliveryId: 50004,
    deliveryCost: 15.0,
    GST: 1500.0,
    paymentHistory: {
      total: 1650.0,
      date: "2025-07-04T07:50:00Z",
      transactionId: "pi_4STU901VWX234",
      via: "PayPal",
    },
    driverInfo: { name: "George Brown", mobile: "+61400222333" },
    jobRefrence: { code: "JR004", projectName: "Stadium Lighting" },
    address: {
      addressId: "addr004",
      title: "Stadium Entrance",
      streetAddress: "123 Sports Rd",
      suburb: "Brisbane",
      state: "QLD",
      postcode: "4000",
    },
    recipientInfo: {
      recipientName: "Hannah Smith",
      recipientMobile: "+61799887766",
    },
    flashings: [
      {
        flashingId: "fl004",
        code: "FL-D4",
        position: "D4",
        material: "Aluminum",
        color: "White",
        thickness: 1.0,
        crushfold: true,
        tapered: false,
        totalGirth: 700,
        sepcifications: [
          { pieceId: "p005", quantity: 6, length: 600, cost: 720.0 },
        ],
      },
    ],
  },
  // 5. Cancelled Delivery, Cancelled
  {
    orderId: 100005,
    orderDateTime: "2025-07-05T11:20:00Z",
    orderProgress: "Order Review",
    orderStatus: "Cancelled",
    deliveryType: "delivery",
    deliveryDate: "2025-07-08",
    deliveryId: 50005,
    deliveryCost: 10.0,
    GST: 1000.0,
    paymentHistory: {
      total: 1100.0,
      date: "2025-07-05T11:25:00Z",
      transactionId: "pi_5YZA567BCD890",
      via: "Card",
    },
    driverInfo: { name: "Isaac Newton", mobile: "+61400123456" },
    jobRefrence: { code: "JR005", projectName: "Library Expansion" },
    address: {
      addressId: "addr005",
      title: "Community Library",
      streetAddress: "78 Book Ln",
      suburb: "Adelaide",
      state: "SA",
      postcode: "5000",
    },
    recipientInfo: {
      recipientName: "Julia Roberts",
      recipientMobile: "+61812345678",
    },
    rejectionDesc: "Client cancelled before production started",
    flashings: [
      {
        flashingId: "fl005",
        code: "FL-E5",
        position: "E5",
        material: "Copper",
        color: "Green Matte",
        thickness: 1.5,
        crushfold: false,
        tapered: true,
        totalGirth: 650,
        sepcifications: [
          { pieceId: "p006", quantity: 2, length: 450, cost: 360.0 },
        ],
      },
    ],
  },
  // 6. Requested Pickup, Requested
  {
    orderId: 100006,
    orderDateTime: "2025-07-06T14:10:00Z",
    orderProgress: "Order Review",
    orderStatus: "Requested",
    deliveryType: "pickup",
    deliveryDate: "2025-07-07",
    deliveryId: 50006,
    deliveryCost: 0.0,
    GST: 0.0,
    paymentHistory: {
      total: 100.0,
      date: "2025-07-06T14:15:00Z",
      transactionId: "pi_6FGH123IJK456",
      via: "Crypto",
    },
    driverInfo: { name: "Karen Gillan", mobile: "+61398765432" },
    jobRefrence: { code: "JR006", projectName: "Campus Signage" },
    pickupInfo: {
      addressId: "pu002",
      title: "Upper Depot",
      streetAddress: "50 Depot Rd",
      suburb: "Perth",
      state: "WA",
      postcode: "6000",
      description: "Mon-Sat, 7am-7pm",
    },
    recipientInfo: {
      recipientName: "Liam Neeson",
      recipientMobile: "+61887654321",
    },
    flashings: [
      {
        flashingId: "fl006",
        code: "FL-F6",
        position: "F6",
        material: "Steel",
        color: "Gray",
        thickness: 2.2,
        crushfold: true,
        tapered: true,
        totalGirth: 820,
        sepcifications: [
          { pieceId: "p007", quantity: 12, length: 250, cost: 600.0 },
        ],
      },
    ],
  },
  // 7. Completed Delivery, Completed
  {
    orderId: 100007,
    orderDateTime: "2025-07-07T10:05:00Z",
    orderProgress: "Completed",
    orderStatus: "Completed",
    deliveryType: "delivery",
    deliveryDate: "2025-07-07",
    deliveryId: 50007,
    deliveryCost: 7.5,
    GST: 750.0,
    paymentHistory: {
      total: 825.0,
      date: "2025-07-07T10:10:00Z",
      transactionId: "pi_7LMN789OPQ012",
      via: "Bank Transfer",
    },
    driverInfo: { name: "Mike Tyson", mobile: "+61400444333" },
    jobRefrence: { code: "JR007", projectName: "Bridge Inspection" },
    address: {
      addressId: "addr007",
      title: "Bridge Access",
      streetAddress: "10 River Rd",
      suburb: "Darwin",
      state: "NT",
      postcode: "0800",
    },
    recipientInfo: {
      recipientName: "Nina Dobrev",
      recipientMobile: "+61876543210",
    },
    flashings: [
      {
        flashingId: "fl007",
        code: "FL-G7",
        position: "G7",
        material: "Aluminum",
        color: "White",
        thickness: 1.0,
        crushfold: false,
        tapered: false,
        totalGirth: 680,
        sepcifications: [
          { pieceId: "p008", quantity: 4, length: 350, cost: 400.0 },
        ],
      },
      {
        flashingId: "fl020",
        code: "FL-G7",
        position: "G7",
        material: "Copper",
        color: "Black Matte",
        thickness: 1.0,
        crushfold: false,
        tapered: false,
        totalGirth: 680,
        sepcifications: [
          { pieceId: "p025", quantity: 4, length: 350, cost: 400.0 },
          { pieceId: "p050", quantity: 4, length: 350, cost: 400.0 },
        ],
      },
    ],
  },
  // 8. Rejected Pickup, Rejected
  {
    orderId: 100008,
    orderDateTime: "2025-07-08T16:20:00Z",
    orderProgress: "In Production",
    orderStatus: "Rejected",
    deliveryType: "pickup",
    deliveryDate: "2025-07-09",
    deliveryId: 50008,
    deliveryCost: 0.0,
    GST: 0.0,
    paymentHistory: {
      total: 300.0,
      date: "2025-07-08T16:25:00Z",
      transactionId: "pi_8RST345UVW678",
      via: "Card",
    },
    driverInfo: { name: "Olivia Wilde", mobile: "+61355566777" },
    jobRefrence: { code: "JR008", projectName: "Mall Expansion" },
    pickupInfo: {
      addressId: "pu003",
      title: "West Depot",
      streetAddress: "88 Warehouse Blvd",
      suburb: "Hobart",
      state: "TAS",
      postcode: "7000",
      description: "Tue-Sun, 9am-5pm",
    },
    recipientInfo: {
      recipientName: "Peter Parker",
      recipientMobile: "+61333322111",
    },
    rejectionDesc: "Materials out of stock",
    flashings: [
      {
        flashingId: "fl008",
        code: "FL-H8",
        position: "H8",
        material: "Copper",
        color: "Brown",
        thickness: 2.5,
        crushfold: true,
        tapered: false,
        totalGirth: 720,
        sepcifications: [
          { pieceId: "p009", quantity: 6, length: 450, cost: 450.0 },
        ],
      },
    ],
  },
];

export const replacementRequests: ReplacementRequest[] = [
  {
    requestId: 65802343,
    order: {
      orderId: 45678920,
      orderDateTime: "2025-07-01T08:15:00Z",
      orderProgress: "In Production",
      orderStatus: "Pending",
      deliveryType: "pickup",
      deliveryDate: "2025-07-03",
      deliveryId: 58721,
      driverInfo: {
        name: "Alice Martin",
        mobile: "+61400111222",
      },
      jobRefrence: {
        code: "JR001",
        projectName: "City Mall Fitout",
      },
      // address: {
      //   addressId: 'addr001',
      //   title: 'Site Office',
      //   streetAddress: '45 King St',
      //   suburb: 'Sydney',
      //   state: 'NSW',
      //   postcode: '2000',
      // },
      pickupInfo: {
        addressId: "pu001",
        title: "Main Depot",
        streetAddress: "200 Industrial Ave",
        suburb: "Melbourne",
        state: "VIC",
        postcode: "3000",
        description: "Open: 8am - 6pm",
      },
      recipientInfo: {
        recipientName: "Bob Lee",
        recipientMobile: "+61400999888",
      },
    }, // now wrapped in `order`
    requestStatus: "Ready for pickup",
    requestDateTime: "2025-06-07T09:06:00Z",
    requestProgress: "Ready",
    requestDeliveryId: 223322,
    requestPieces: [
      {
        flashingId: "hw2k",
        material: "Copper",
        color: "Black Matte",
        thickness: 1.2,
        totalGirth: 600,
        pieceId: "hw2kl0o8",
        quantity: 2,
        length: 2000,
        cost: 1200.0,
      },
      {
        flashingId: "hw2k",
        material: "Copper",
        color: "Black Matte",
        thickness: 1.2,
        totalGirth: 600,
        pieceId: "hw2k123s",
        quantity: 4,
        length: 1250,
        cost: 1200.0,
      },
      {
        flashingId: "a5s6d",
        material: "Stainless Steel",
        color: "Steel",
        thickness: 1.5,
        totalGirth: 700,
        pieceId: "a5s6dghu7",
        quantity: 4,
        length: 300,
        cost: 1200.0,
      },
    ],
    issue: {
      title: "Wrong size or dimensions",
      desc: "I received my order, but one item doesn't match the specified measurements",
      value: "wrong-size",
    },
    rejectDesc: "Your replacement request description doesn't meet the needs",
    description: `Please replace the mismatched item.`,
    photos: [
      { photoId: "s6a7a", src: "http://domain.com/photo1.jpg" },
      { photoId: "s6a7b", src: "http://domain.com/photo2.jpg" },
    ],
  },
  // ✅ New Replacement Request for Order ID 100001
  {
    requestId: 90000000,
    requestProgress: "Requested",
    requestDeliveryId: 90873,
    order: {
      orderId: 100001,
      orderDateTime: "2025-07-01T08:15:00Z",
      orderProgress: "Order Review",
      orderStatus: "Pending",
      deliveryType: "delivery",
      deliveryDate: "2025-07-03",
      deliveryId: 50001,
      driverInfo: {
        name: "Alice Martin",
        mobile: "+61400111222",
      },
      jobRefrence: {
        code: "JR001",
        projectName: "City Mall Fitout",
      },
      address: {
        addressId: "addr001",
        title: "Site Office",
        streetAddress: "45 King St",
        suburb: "Sydney",
        state: "NSW",
        postcode: "2000",
      },
      recipientInfo: {
        recipientName: "Bob Lee",
        recipientMobile: "+61400999888",
      },
    },
    requestStatus: "Requested",
    requestDateTime: "2025-08-07T09:00:00Z",
    requestPieces: [
      {
        flashingId: "fl001",
        material: "Aluminum",
        color: "Silver",
        thickness: 1.2,
        totalGirth: 600,
        pieceId: "p001",
        quantity: 10,
        length: 150,
        cost: 300.0,
      },
    ],
    issue: {
      title: "Wrong size or dimensions",
      desc: "Item received has incorrect measurements",
      value: "wrong-size",
    },
    description: "Please replace the item as it doesn’t match the specs.",
    photos: [
      { photoId: "ph90000000a", src: "http://domain.com/photo1.jpg" },
      { photoId: "ph90000000b", src: "http://domain.com/photo2.jpg" },
    ],
  },
  // ✅ New Replacement Request for Order ID 100002
  {
    requestId: 90000001,
    requestProgress: "In Production",
    requestDeliveryId: 32132,
    order: {
      orderId: 100002,
      orderDateTime: "2025-07-02T12:00:00Z",
      deliveryType: "delivery",
      deliveryDate: "2025-07-05",
      deliveryId: 50002,
      driverInfo: {
        name: "Carlos Ruiz",
        mobile: "+61400777666",
      },
      jobRefrence: {
        code: "JR002",
        projectName: "Harbour Bridge Maintenance",
      },
      address: {
        addressId: "addr002",
        title: "Maintenance Yard",
        streetAddress: "1 Bridge Rd",
        suburb: "Sydney",
        state: "NSW",
        postcode: "2009",
      },
      recipientInfo: {
        recipientName: "Dana Scott",
        recipientMobile: "+61400666555",
      },
    },
    requestStatus: "In Production",
    requestDateTime: "2025-08-07T09:00:00Z",
    requestPieces: [
      {
        flashingId: "fl002",
        material: "Copper",
        color: "Copper Red",
        thickness: 1.8,
        totalGirth: 750,
        pieceId: "p002",
        quantity: 5,
        length: 400,
        cost: 450.0,
      },
      {
        flashingId: "fl002",
        material: "Copper",
        color: "Copper Red",
        thickness: 1.8,
        totalGirth: 750,
        pieceId: "p003",
        quantity: 3,
        length: 800,
        cost: 540.0,
      },
    ],
    issue: {
      title: "Wrong size or dimensions",
      desc: "Item received has incorrect measurements",
      value: "wrong-size",
    },
    description: "Please replace the item as it doesn’t match the specs.",
    photos: [
      { photoId: "ph90000001a", src: "http://domain.com/photo1.jpg" },
      { photoId: "ph90000001b", src: "http://domain.com/photo2.jpg" },
    ],
  },
];
